# Generated by Django 4.0.8 on 2025-05-07 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_course_summary_kk_course_title_kk_program_summary_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Бастаушы'), ('Advanced', 'Жетілдірілген')], max_length=25),
        ),
    ]
