# Generated by Django 4.2.21 on 2025-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0006_alter_course_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.CharField(
                choices=[
                    ("Первый", "Первый"),
                    ("Второй", "Второй"),
                    ("Третий", "Третий"),
                ],
                max_length=200,
            ),
        ),
    ]
