# Generated by Django 4.0.8 on 2025-05-07 09:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_choice_choice_text_kk_question_content_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='A detailed description of the quiz', verbose_name='Description'),
        ),
    ]
