# Generated by Django 4.2.21 on 2025-05-10 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0009_alter_programcode_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcode",
            name="pass_mark",
            field=models.SmallIntegerField(
                default=50,
                help_text="Percentage required to pass exam.",
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Pass Mark",
            ),
        ),
    ]
