# Generated by Django 4.2.21 on 2025-05-10 11:08

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("result", "0004_alter_result_semester"),
        ("quiz", "0010_programcode_pass_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="programcode",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="result.takencourse",
            ),
        ),
        migrations.AddField(
            model_name="programcode",
            name="point",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=5
            ),
        ),
    ]
