# Generated by Django 4.2.21 on 2025-05-10 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("result", "0004_alter_result_semester"),
        ("quiz", "0011_programcode_grade_programcode_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programcode",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="programs",
                to="result.takencourse",
            ),
        ),
    ]
