# Generated by Django 4.2.21 on 2025-05-11 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_alter_programcode_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programcode",
            name="pass_mark",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Percentage required to pass exam.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(100)],
                verbose_name="Pass Mark",
            ),
        ),
    ]
