# Generated by Django 4.2.21 on 2025-05-07 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="level",
            field=models.CharField(
                choices=[("7 class", "7 class"), ("8 class", "8 class")],
                max_length=25,
                null=True,
            ),
        ),
    ]
